language: node_js

git:
  submodules: false

os: linux
dist: xenial
sudo: enabled

script:
        - npm test
        - nvm install 10.15 && nvm exec 10.15
        - npm run lint-check
        - npm run spellcheck
