language: node_js

git:
  submodules: false

os: linux
dist: xenial
sudo: enabled

script:
        - npm test
        - npm run build && npm run test:karma
        - nvm install 10.15 && nvm use 10.15
        - npm run lint-check
        - npm run spellcheck

